export const cards = [
    { id: 1, left: 0, right: 0, value: 0, identical: true, icon : '*', class: null},
    { id: 2, left: 0, right: 1, value: 1, icon : '*', class: null},
    { id: 3, left: 0, right: 2, value: 2, icon : '*', class: null},
    { id: 4, left: 0, right: 3, value: 3, icon : '*', class: null},
    { id: 5, left: 0, right: 4, value: 4, icon : '*', class: null},
    { id: 6, left: 0, right: 5, value: 5, icon : '*', class: null},
    { id: 7, left: 0, right: 6, value: 6, icon : '*', class: null},
    { id: 8, left: 1, right: 1, value: 2, identical: true, icon : '*', class: null},
    { id: 9, left: 1, right: 2, value: 3, icon : '*', class: null},
    { id: 10, left: 1, right: 3, value: 4, icon : '*', class: null},
    { id: 11, left: 1, right: 4, value: 5, icon : '*', class: null},
    { id: 12, left: 1, right: 5, value: 6, icon : '*', img: 'icons8-domino-32png', class: null},
    { id: 13, left: 1, right: 6, value: 7, icon : '*', class: null},
    { id: 14, left: 2, right: 2, value: 4, identical: true, icon : '*', class: null},
    { id: 15, left: 2, right: 3, value: 5, icon : '*', class: null},
    { id: 16, left: 2, right: 4, value: 6, icon : '*', class: null},
    { id: 17, left: 2, right: 5, value: 7, icon : '*', class: null},
    { id: 18, left: 2, right: 6, value: 8, icon : '*', class: null},
    { id: 19, left: 3, right: 3, value: 6, identical: true, icon : '*', class: null},
    { id: 20, left: 3, right: 4, value: 7, icon : '*', class: null},
    { id: 21, left: 3, right: 5, value: 8, icon : '*', class: null},
    { id: 22, left: 3, right: 6, value: 9, icon : '*', class: null},
    { id: 23, left: 4, right: 4, value: 8, identical: true, icon : '*', class: null},
    { id: 24, left: 4, right: 5, value: 9, icon : '*', class: null},
    { id: 25, left: 4, right: 6, value: 10, icon : '*', class: null},
    { id: 26, left: 5, right: 5, value: 10, identical: true, icon : '*', class: null},
    { id: 27, left: 5, right: 6, value: 11, icon : '*', class: null},
    { id: 28, left: 6, right: 6, value: 12, identical: true, icon : '*', class: null},
]
